# Generated by Django 3.1.7 on 2021-03-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogv2_app', '0002_auto_20210304_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sum',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
